package utils

const (
	//默认返回
	RECODE_CODE_UNKNOWER = "100"
	////////////////回复状态码及信息定义//////////
	RESP_CODE_OK              = "2000"
	RESP_CODE_GETJSONERR      = "2001"
	RESP_CODE_JSON_DATANULL   = "2002"
	RESP_CODE_DATAISEXISTS    = "2003"
	RESP_CODE_DATAISNOTEXISTS = "2005"
	RESP_CODE_CERATE_ERR      = "2006"
	RESP_CODE_DEL_ERR         = "2007"
	RESP_CODE_UPDATE          = "2008"
	RESP_CODE_SELECT          = "2009"
	///////////////INFO/////////////////////
	RECODE_INFO_UNKNOWERR = "为知错误"
	//返回信息的描述
	RESP_INFO_OK              = "成功"
	RESP_INFO_GETJSONERR      = "无法获取JSON中数据"
	RESP_INFO_JSON_DATANULL   = "JSON中获取的数据为NULL"
	RESP_INFO_DATAISEXISTS    = "数据已存在"
	RESP_INFO_DATAISNOTEXISTS = "数据不存在"

	//////////////日志按业务定义//////////////////
	//文章错误提示
	LOG_ARTICLE_ADD_ERR            = "[ARTICLE_ADD_ERR:--->]"
	LOG_ARTICLE_DELETE_ERR         = "[ARTICLE_DELETE_ERR:--->]"
	LOG_ARTICLE_EDIT_ERR           = "[ARTICLE_EDIT_ERR:--->]"
	LOG_ARTICLE_LIST_BYTAG_ERR     = "[ARTICLE_LIST_BYTAG_ERR:--->]"
	LOG_ARTICLE_LIST_BYCOLUMN_ERR  = "[ARTICLE_LIST_BYCOLUMN_ERR:--->]"
	LOG_ARTICLE_SUBMIT_ERR         = "[ARTICLE_SUBMIT_ERR:--->]"
	LOG_ARTICLE_GETWILLBESUB_ERR   = "[ARTICLE_GETWILLBESUB_ERR:--->]"
	LOG_ARTICLE_RELEASE_ERR        = "[ARTICLE_RELEASE_ERR:--->]"
	LOG_ARTICLE_GETRELEASELIST_ERR = "[ARTICLE_GETRELEASELIST_ERR:--->]"
	LOG_ARTICLE_RELEASEFAILD_ERR   = "[ARTICLE_RELEASEFAILD_ERR:--->]"
	//用户提示
	LOG_USER_REGISTER_ERR      = "[USER_REGISTER_ERR:--->]"
	LOG_USER_LOGIN_ERR         = "[USER_LOGIN_ERR:--->]"
	LOG_USER_ADD_ERR           = "[USER_ADD_ERR:--->]"
	LOG_USER_DELETE_ERR        = "[USER_DELETE_ERR:--->]"
	LOG_USER_UPDATE_ROLLER_ERR = "[USER_UPDATE_ROLLER_ERR:--->]"
	LOG_USER_CNAME_ERR         = "[USER_CNAME_ERR:--->]"
	LOG_USER_ISEXISTS          = "用户已存在"
	LOG_USER_CREATE_OK         = "用户创建成功"

	//专题错误提示
	LOG_COLUMN_ADD_ERR    = "[COLUMN_ADD_ERR:--->]"
	LOG_COLUMN_DELETE_ERR = "[COLUMN_DELETE_ERR:--->]"
	LOG_COLUMN_LIST_ERR   = "[COLUMN_LIST_ERR:--->]"
	LOG_COLUMN_CNAME_ERR  = "[COLUMN_CNAME_ERR:--->]"
	//标签错误提示
	LOG_TAG_ADD_ERR    = "[TAG_ADD_ERR:--->]"
	LOG_TAG_DELETE_ERR = "[TAG_DELETE_ERR:--->]"
	LOG_TAG_CNAME_ERR  = "[TAG_CNAME_ERR:--->]"
	//数据库错误
	DB_CREATE_ERR = "数据库插入错误"
)
